### ISSUE TITLE
ImportError: cannot import name FlaskRedis

### ISSUE THREAD

**Issue by kirang89** [underyx/flask-redis#22]
I am trying to import FlaskRedis into my flask application using ```from flask.ext.redis import FlaskRedis``` but it fails. Here is my pip freeze: 

```
Flask-Redis==0.0.6
redis==2.10.3
```

Am I missing something obvious here ?

**Comment by dhesson** [comment]
I'm having the same issue.  Also in PyPi and in the build server I see version 0.1.0 but it pulls 0.0.6 and 0.0.6 appears to be either broken or doesn't contain FlaskRedis.

**Comment by underyx** [comment]
The issue seems to be with `pip install flask-redis` downloading an old version, but I am not able to reproduce it. What are your Python, pip, and setuptools versions?

**Comment by kirang89** [comment]
Python 2.7.10 and pip 1.4.1

**Comment by underyx** [comment]
Wow, that's amazingly old. You probably aren't able to install wheels then. I guess I'll have to upload a source distribution to PyPI in a bit.

**Comment by underyx** [comment]
I've uploaded a zip of the source to pypi, and pip 1.4.1 correctly installed it with `pip install flask-redis`. Can you guys try to install it again?

**Comment by kirang89** [comment]
Damn, I noticed that I have pip 7.1.2 in my system but 1.4.1 in my virtualenv. It works on 1.4.1 now. Thanks for the fix and pointing out the obsolete version!

**Comment by underyx** [comment]
You got it :smile_cat:

**Comment by dhesson** [comment]
Yeah my virtualenv has pip 1.4.1 and python 2.7.10.  Thanks for the fix.
